# Generated by Django 4.2.20 on 2025-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('muscles_targeted', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Biceps',
        ),
    ]
