# Generated by Django 4.2.20 on 2025-06-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0002_exercises_delete_biceps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
    ]
